local whiteAlpha = 0

function onCreate()
whiteAlpha = getModSetting("gameboyAlpha", 'Kirby Hud')
debugPrint(whiteAlpha)
makeLuaSprite('whiteBackground', '', 0, 660)
makeGraphic('whiteBackground', 2500, 300, 'FFFFFF')
setObjectCamera('whiteBackground','hud')
addLuaSprite('whiteBackground')

makeLuaSprite('sc', 'KDLH/score', 350, 660)
setObjectCamera('sc','hud')
setGraphicSize("sc", 70)
setProperty('sc.antialiasing', false)
addLuaSprite('sc')

makeLuaText('ScoreKirby', '0', getTextWidth('scoreTxt'), 490, 660)
setTextFont('ScoreKirby', 'Kirbys-Adventure.ttf') 
setTextAlignment("ScoreKirby", 'left')
setTextSize('ScoreKirby', 25)
setTextBorder("ScoreKirby", 0, 'FFFFFF')  
setObjectCamera('ScoreKirby','hud')
setTextColor("ScoreKirby", "000000")
addLuaText('ScoreKirby') 

makeLuaText('missesKirby', 'X0', getTextWidth('scoreTxt'), 740,680)
setTextFont('missesKirby', 'Kirbys-Adventure.ttf') 
setTextAlignment("missesKirby", 'right')
setTextSize('missesKirby', 25)
setTextBorder("missesKirby", 0, 'FFFFFF')  
setObjectCamera('missesKirby','hud')
setTextColor("missesKirby", "000000")
addLuaText('missesKirby') 

makeLuaText('PlayerTxt', boyfriendName.. '    '..math.floor(getProperty("health") * 50)..'%', getTextWidth('scoreTxt'), 320, 690)
setTextFont('PlayerTxt', 'Kirbys-Adventure.ttf') 
setTextAlignment("PlayerTxt", 'left')
setTextSize('PlayerTxt', 25)
setTextBorder("PlayerTxt", 0, 'FFFFFF')  
setObjectCamera('PlayerTxt','hud')
setTextColor("PlayerTxt", "000000")
addLuaText('PlayerTxt') 
end

function onUpdate(elapsed)
setTextString('ScoreKirby', score)
setTextString('missesKirby', 'X'..misses)
setTextString('PlayerTxt', boyfriendName.. '    '..math.floor(getProperty("health") * 50)..'%')
setProperty('whiteBackground.alpha', whiteAlpha)
end
function onUpdatePost(elapsed)
setProperty('iconP1.y', 620)
setProperty('iconP1.x', 640) 
setGraphicSize("iconP1", 70)
setProperty('iconP2.visible', false)  
setProperty('scoreTxt.visible', false)
setProperty('healthBar.visible', false)
setProperty('timeBar.visible', false)
setProperty('timeTxt.visible', false)
end